# trabajar con secretos y estos estan encriptados, se usan para almacenar informacion sensible como contraseñas, tokens, etc

# https://kubernetes.io/docs/concepts/configuration/secret/

apiVersion: v1
kind: Secret # tipo de dato
metadata:
  name: backend-secrets # nombre para poder indentificar el secreto
type: Opaque # tipo de secreto, opaque es el mas comun para almacenar datos arbitrarios
data:

# se puede usar esto en termina tambien para convertir
# echo -n "postgres" | base64

# Base64 String superman@google.com 
  JWT_SECRET: c3VwZXJtYW5AZ29vZ2xlLmNvbQ==
  # https://codebeautify.org/base64-encode conversor a base64, el valor de la contraseña debe ser codificado en base64
