# trabajar con secretos y estos estan encriptados, se usan para almacenar informacion sensible como contraseñas, tokens, etc

# https://kubernetes.io/docs/concepts/configuration/secret/

apiVersion: v1
kind: Secret # tipo de dato
metadata:
  name: postgres-secrets # nombre para poder indentificar el secreto
type: Opaque # tipo de secreto, opaque es el mas comun para almacenar datos arbitrarios
data:
  DB_USER: postgres
  DB_PASSWORD: EstoEsUnPasswordSecreto