# trabajar con secretos y estos estan encriptados, se usan para almacenar informacion sensible como contraseñas, tokens, etc

# https://kubernetes.io/docs/concepts/configuration/secret/

apiVersion: v1
kind: Secret # tipo de dato
metadata:
  name: postgres-secrets # nombre para poder indentificar el secreto
type: Opaque # tipo de secreto, opaque es el mas comun para almacenar datos arbitrarios
data:

# se puede usar esto en termina tambien para convertir
# echo -n "postgres" | base64

# Base64 String postgres = cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  # https://codebeautify.org/base64-encode conversor a base64, el valor de la contraseña debe ser codificado en base64
  # Base64 String EstoEsUnPasswordSecreto = RXN0b0VzVW5QYXNzd29yZFNlY3JldG8=
  DB_PASSWORD: RXN0b0VzVW5QYXNzd29yZFNlY3JldG8=
