# nuestro deployment de postgres
# este es nuestro blueprint o plano
# es nuestra plantilla para crear nuestros pods

# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment # el nombre del deployment
  labels:
    app: postgres
spec: # definicion de nuestro pod
  replicas: 1 # copias del pod
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15.1
        ports:
        - containerPort: 5432
        env: # se manajea con key value pairs
        - name: POSTGRES_PASSWORD
          valueFrom: # busca el valor de la variable de entorno en un secret
            secretKeyRef: # es un secretKeyRef porque es un secreto
              name: postgres-secrets # el nombre del secret que creamos
              key: DB_PASSWORD