# nuestro deployment de postgres
# este es nuestro blueprint o plano
# es nuestra plantilla para crear nuestros pods

# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment # el nombre del deployment
  labels:
    app: postgres
spec: # definicion de nuestro pod
  replicas: 1 # copias del pod
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15.1
        ports:
        - containerPort: 5432
        env: # se manajea con key value pairs
        - name: POSTGRES_PASSWORD
          valueFrom: # busca el valor de la variable de entorno en un secret
            secretKeyRef: # es un secretKeyRef porque es un secreto
              name: postgres-secrets # el nombre del secret que creamos
              key: DB_PASSWORD
--- # nuevo archivo abajo

# servicio lo dejamos por aca por que siempre va estar de la mano con deployments

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
  # tcp es el protocolo que se va a usar para la comunicacion entre el servicio y el deployment
    - protocol: TCP
      port: 5432 # cualquier puerto, es el puerto que todo aquel afuera tendra que utilizar
      # para conectarse al puerto 5432 que tengo enlzado con el contenedor
      targetPort: 5432 
